# Data
dataset_name: 'python_code_search'
#训练集位置
trainset: '/root/autodl-tmp/data/python/final/jsonl/train/graph_train_gnn.jsonl.gz'
#验证集位置
devset: '/root/autodl-tmp/data/python/final/jsonl/valid/graph_valid_gnn.jsonl.gz'
#测试集位置
testset: '/root/autodl-tmp/data/python/final/jsonl/test/graph_test_gnn.jsonl.gz'
#向量初始化
vector_db: '/root/autodl-tmp/data/python_base_gz/'
saved_vocab_file: '/root/autodl-tmp/project/mmcs_nn/network/vocabs/python_vocab_150k_3fre_codenet_100.pkl'
#初始词嵌入位置
pretrained_word_embed_file:
pretrained:
# 输出位置
out_dir:  '/root/autodl-tmp/project/network/models'




# 预处理参数
top_word_vocab: 150000
min_word_freq: 3


model_name: 'MMCS'

# 词嵌入信息
word_embed_dim: 100
fix_word_embed: False
edge_embed_dim: 32

graph_hidden_size: 100


word_dropout: 0.3
enc_rnn_dropout: 0.3



graph_type: 'gat'
doc_graph_type: 'gat'
graph_hops: 3
graph_direction: 'all'
message_function: 'no_edge'

heads: 2
code_info_type: 'all'
des_info_type: 'all'

# 训练信息
optimizer: 'adam'
learning_rate: 0.01
grad_clipping: 10
grad_accumulated_steps: 1
early_stop_metric: 'MRR'

random_seed: 2024
shuffle: True
max_epochs: 100
batch_size: 256
patience: 10
verbose: 1000

# 测试信息
test_batch_size: 256
save_params: True
logging: True

# 设备信息
no_cuda: False
cuda_id: 0